# Autogenerated Alembic migration script template.
"""${message}"""
from alembic import op  # noqa
import sqlalchemy as sa  # noqa
${imports if imports else ''}

# Revision identifiers, used by Alembic.
revision = ${repr(revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}

def upgrade() -> None:
    ${upgrades if upgrades else 'pass'}

def downgrade() -> None:
    ${downgrades if downgrades else 'pass'}
